#==================================================================================================
#
#  Makefile for the C++ Training
#
#  Copyright (C) 2015-2025 Klaus Iglberger - All Rights Reserved
#
#  This file is part of the C++ training by Klaus Iglberger. The file may only be used in the
#  context of the C++ training or with explicit agreement by Klaus Iglberger.
#
#==================================================================================================


# Build rules
default:
	@echo "\nBuilding all tasks in chapter \"Safe C++\""
	@$(MAKE) --no-print-directory -C ./2_Safe_Cpp


# Cleanup
clean:
	@echo "Cleaning up..."
	@$(MAKE) --no-print-directory -C ./2_Safe_Cpp clean


# Setting the independent commands
.PHONY: default clean
